---
- name: Restart NZBGet process on Windows
  hosts: windows
  tasks:
    - name: Kill NZBGet if running
      ansible.windows.win_shell: |
        Stop-Process -Name nzbget -Force -ErrorAction SilentlyContinue

    - name: Wait 5 seconds
      ansible.windows.win_shell: |
        Start-Sleep -Seconds 5

    - name: Start NZBGet
      ansible.windows.win_shell: |
        Start-Process -FilePath "C:\Program Files\NZBGet\nzbget.exe"


