---
- name: Wait for Docker to stop all containers, then shut down
  hosts: linux
  become: yes
  gather_facts: no

  tasks:

    - name: Reboot the system
      ansible.builtin.command: sudo reboot now
